import turtle as trtl

painter = trtl.Turtle()
painter.fillcolor("gold")
painter.begin_fill()
painter.color("gold")
painter.left(75)
painter.forward(100)
painter.left(30)
painter.forward(100)
painter.left(150)
painter.forward(100)
painter.left(30)
painter.forward(100)
painter.end_fill()

painter.begin_fill()
painter.penup()
painter.goto(96.6, 96.6)
painter.pendown()
painter.left(165)
painter.left(75)
painter.forward(100)
painter.left(30)
painter.forward(100)
painter.left(150)
painter.forward(100)
painter.left(30)
painter.forward(100)
painter.end_fill()
painter.fillcolor("gold")
painter.begin_fill()
painter.color("gold")
painter.left(75)
painter.forward(100)
painter.left(30)
painter.forward(100)
painter.left(150)
painter.forward(100)
painter.left(30)
painter.forward(100)
painter.end_fill()

painter.begin_fill()
painter.penup()
painter.goto(96.6, 96.6)
painter.pendown()
painter.left(165)
painter.left(75)
painter.forward(100)
painter.left(30)
painter.forward(100)
painter.left(150)
painter.forward(100)
painter.left(30)
painter.forward(100)
painter.end_fill()
wn = trtl.Screen()
wn.mainloop()
