#   a113_forward_and_right.py
import turtle as trtl

painter = trtl.Turtle()

painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)
painter.forward(20)
painter.right(20)

wn = trtl.Screen()
wn.mainloop()
